import type {
  AppMarketingBlock,
  CatalogCategory,
  CatalogProduct,
} from "@/types/store";

export const demoMarketing: AppMarketingBlock[] = [
  {
    id: "demo-hero",
    kind: "hero",
    title: "Marketplace Angola",
    subtitle: "Compre e venda com confiança. Negócios perto de si.",
    gradientFrom: "#D62828",
    gradientTo: "#F4A261",
    sortOrder: 0,
  },
];

export const demoCategories: CatalogCategory[] = [
  { id: "eletronicos", name: "Eletrónicos", kind: "product", sortOrder: 0 },
  { id: "moda", name: "Moda", kind: "product", sortOrder: 1 },
  { id: "eletrodomesticos", name: "Eletrodomésticos", kind: "product", sortOrder: 2 },
  { id: "beleza", name: "Beleza", kind: "product", sortOrder: 3 },
  { id: "moveis", name: "Móveis", kind: "product", sortOrder: 4 },
  { id: "carros", name: "Carros", kind: "product", sortOrder: 5 },
  { id: "desporto", name: "Desporto", kind: "product", sortOrder: 6 },
  { id: "servicos", name: "Serviços", kind: "product", sortOrder: 7 },
  { id: "imoveis", name: "Imóveis", kind: "stay", sortOrder: 8 },
  { id: "emprego", name: "Emprego", kind: "job", sortOrder: 9 },
];

const demoSeller = {
  id: "demo-seller",
  displayName: "Vendedor demo",
  photoUrl: null,
};

export const demoProducts: CatalogProduct[] = [
  {
    id: "p-1",
    sellerId: "demo-seller",
    seller: demoSeller,
    categoryId: "eletronicos",
    subcategoryId: "telefones",
    title: "Smartphone Android — 128 GB",
    priceLabel: "185 000 Kz",
    deliveryText: "Luanda, Talatona",
    reviewCount: 0,
    viewCount: 0,
    isOutOfStock: false,
    isFeatured: true,
    sortOrder: 0,
    imageColor: 0xffd62828,
    productMeta: {
      brand: "Samsung",
      model: "Galaxy A54",
      storage: "128",
      condition: "usado_bom",
    },
  },
  {
    id: "p-2",
    sellerId: "demo-seller",
    seller: demoSeller,
    categoryId: "moda",
    subcategoryId: "sapatos",
    title: "Ténis desportivos unissexo",
    priceLabel: "42 500 Kz",
    deliveryText: "Luanda, Maianga",
    reviewCount: 0,
    viewCount: 0,
    isOutOfStock: false,
    isFeatured: true,
    sortOrder: 1,
    imageColor: 0xfff4a261,
    productMeta: {
      gender: "unissexo",
      size: "42",
      brand: "Nike",
      condition: "novo",
    },
  },
  {
    id: "p-3",
    sellerId: "demo-seller",
    seller: demoSeller,
    categoryId: "eletrodomesticos",
    subcategoryId: "cozinha",
    title: "Conjunto de panelas antiaderente",
    priceLabel: "67 900 Kz",
    deliveryText: "Luanda",
    reviewCount: 0,
    viewCount: 0,
    isOutOfStock: false,
    isFeatured: true,
    sortOrder: 2,
    imageColor: 0xff10b981,
    productMeta: {
      productType: "Panelas",
      brand: "Magefesa",
      condition: "novo",
    },
  },
  {
    id: "p-imoveis-1",
    sellerId: "demo-seller",
    seller: demoSeller,
    categoryId: "imoveis",
    title: "Apartamento T2 — Talatona (aluguer)",
    priceLabel: "85 000 Kz/noite",
    deliveryText: "Talatona, Luanda",
    reviewCount: 0,
    viewCount: 0,
    isOutOfStock: false,
    isFeatured: true,
    sortOrder: 0,
    listingKind: "property",
    propertyMeta: {
      propertyType: "apartamento",
      listingIntent: "rent",
      rentPeriod: "daily",
      province: "Luanda",
      municipality: "Belas",
      bairro: "Talatona",
      priceAmount: 85000,
      bedrooms: 2,
      bathrooms: 1,
      areaSqm: 95,
      furnished: true,
      parking: true,
      minNights: 2,
    },
    imageColor: 0xff6366f1,
  },
  {
    id: "p-4",
    sellerId: "demo-seller",
    seller: demoSeller,
    categoryId: "servicos",
    subcategoryId: "reparacao",
    title: "Instalação de ar condicionado",
    priceLabel: "Sob consulta",
    deliveryText: "Luanda",
    reviewCount: 0,
    viewCount: 0,
    isOutOfStock: false,
    isFeatured: true,
    sortOrder: 3,
    imageColor: 0xff6b6b6b,
    productMeta: {
      serviceArea: "Climatização",
      coverage: "Grande Luanda",
    },
  },
];
