/** Common beauty / cosmetics brands (AO marketplace suggestions). */
export const BEAUTY_BRANDS: readonly string[] = [
  "MAC",
  "Maybelline",
  "L'Oréal",
  "Nivea",
  "Dove",
  "Garnier",
  "NYX",
  "Revlon",
  "Avon",
  "Oriflame",
  "The Ordinary",
  "CeraVe",
  "Neutrogena",
  "Ponds",
  "Vaseline",
  "Black Opal",
  "Dark and Lovely",
  "SoftSheen-Carson",
  "Fenty Beauty",
  "e.l.f.",
  "Essence",
  "Catrice",
  "Rimmel",
  "Chanel",
  "Dior",
  "Yves Saint Laurent",
  "Estée Lauder",
  "Clinique",
  "Lancôme",
  "Paco Rabanne",
  "Hugo Boss",
  "Calvin Klein",
  "Carolina Herrera",
  "Versace",
  "Armani",
  "Local / artesanal",
  "Outra",
] as const;
