/** Motorcycle / scooter brands common in Angola and worldwide. */
export const MOTO_BRANDS: readonly string[] = [
  "Honda",
  "Yamaha",
  "Suzuki",
  "Kawasaki",
  "Bajaj",
  "TVS",
  "Hero",
  "Haojue",
  "Lifan",
  "Kymco",
  "Piaggio",
  "Vespa",
  "BMW",
  "Harley-Davidson",
  "Ducati",
  "KTM",
  "Royal Enfield",
  "Triumph",
  "CFMoto",
  "Zontes",
  "Keeway",
  "Shineray",
  "Dayun",
  "Jialing",
  "Senke",
  "Loncin",
  "Aprilia",
  "Benelli",
  "Indian",
  "Husqvarna",
  "GasGas",
  "MV Agusta",
  "Moto Guzzi",
  "SYM",
  "Peugeot",
  "Gilera",
  "Sanyang",
  "Outra"
] as const;
